# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app handler.go

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: app
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
      
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: app
        path: .
      
    - name: Install Azure Functions Core Tools
      run: |
        npm install -g azure-functions-core-tools@3 --unsafe-perm=true
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Deploy to Azure Functions
      run: |
       func azure functionapp publish goprac --build --no-build


    # - name: 'Deploy'
    #   uses: Azure/functions-action@v1.5.1
    #   id: fa
    #   with:
    #     app-name: goprac
    #     respect-funcignore: true
    #     publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

